### ISSUE TITLE
Failed Processing of .CSV

### ISSUE THREAD

**Issue by jameslashmar** [nicrivard/readwise2directory#5]
The script now spins up, prompts me to download, to which i chose the import directory for the .CSV and then it consequently fails with the following:

DevTools listening on ws://127.0.0.1:63027/devtools/browser/ef204153-f3ab-4645-a1db-d8d19aa0cdb1
Logging into readwise using credentials provided in readwiseMetadata
Log-in successful! Redirecting to export page...
Redirect successful! Waiting for CSV export...
Waiting for download to complete...
Opening a new tab and redirecting to chrome://downloads...
Download complete! Fetching filename from the last download...
readwise-data.csv successfully added to H:\Dropbox\Obsidian\PRISM\.obsidian\scripts\readwise2directory-master
Closing Chrome browser window...
Traceback (most recent call last):
  File "H:\Dropbox\Obsidian\PRISM\.obsidian\scripts\readwise2directory-master\readwise-GET.py", line 1314, in <module>
    fetchTagsIndividuallyOrInBulk() # Function to determine whether to fetch tags individually or in bulk
  File "H:\Dropbox\Obsidian\PRISM\.obsidian\scripts\readwise2directory-master\readwise-GET.py", line 1291, in fetchTagsIndividuallyOrInBulk
    runExtractDataFromApi(list_Highlight, list_BookTitle, list_BookAuthor, list_AmazonBookId, list_Note, list_Color, list_Tags, list_LocationType, \
  File "H:\Dropbox\Obsidian\PRISM\.obsidian\scripts\readwise2directory-master\readwise-GET.py", line 832, in runExtractDataFromApi
    allHighlightsToFetchTagsForSortByDate = sorted(allHighlightsToFetchTagsFor, key = itemgetter('highlighted_at'))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

**Comment by nicrivard** [comment]
Oooh that looks like an interesting issue because it implies that one or more highlights are missing a 'highlighted at' field.

I'll look into this tonight and hopefully push a fix imminently. It seems you're almost there with running this completely !

**Comment by nicrivard** [comment]
@jameslashmar I think I've fixed this now. I was able to replicate the same error message by having at least one `highlighted_at` field = `None`, and I've tweaked the code in [release v1.4](https://github.com/nicrivard/readwise2directory/releases/tag/v1.4) so that it will still return the `id` to fetch tags for.

Give it another go, and let me know if you come across any more issues!

**Comment by jameslashmar** [comment]
Bingo, thanks for this. Can confirm this fixed the issue.

Output for transparency.

```
python3 H:\Dropbox\Obsidian\PRISM\.obsidian\scripts\readwise2directory-master\readwise-GET.py
Importing variables from readwiseMetadata...
Checking if a valid dateFrom variable is defined in readwiseMetadata...
Checking if a valid targetDirectory variable is defined in readwiseMetadata...
Creating sourceDirectory variable from absolute path for this file...
H:\Dropbox\Obsidian\PRISM\.obsidian\scripts\readwise2directory-master directory variable defined
Loading data from JSON files in readwiseCategories to categoriesObject...
Fetching book data from readwise...
Converting readwise book data returned into JSON...
Sorting readwise book data by category...
Grouping readwise book data by category...
Appending readwise book data returned to categoriesObject...
1/11 books added or updated
2/11 books added or updated
3/11 books added or updated
4/11 books added or updated
5/11 books added or updated
6/11 books added or updated
7/11 books added or updated
8/11 books added or updated
9/11 books added or updated
10/11 books added or updated
11/11 books added or updated
Fetching highlight data from readwise...
Converting readwise highlight data returned into JSON...
Sorting readwise highlight data by category...
Grouping readwise highlight data by category...
Appending readwise highlight data returned to categoriesObject...
1/181 highlights added or updated
2/181 highlights added or updated
3/181 highlights added or updated
4/181 highlights added or updated
5/181 highlights added or updated
6/181 highlights added or updated
7/181 highlights added or updated
8/181 highlights added or updated
9/181 highlights added or updated
10/181 highlights added or updated
11/181 highlights added or updated
12/181 highlights added or updated
13/181 highlights added or updated
14/181 highlights added or updated
15/181 highlights added or updated
16/181 highlights added or updated
17/181 highlights added or updated
18/181 highlights added or updated
19/181 highlights added or updated
20/181 highlights added or updated
21/181 highlights added or updated
22/181 highlights added or updated
23/181 highlights added or updated
24/181 highlights added or updated
25/181 highlights added or updated
26/181 highlights added or updated
27/181 highlights added or updated
28/181 highlights added or updated
29/181 highlights added or updated
30/181 highlights added or updated
31/181 highlights added or updated
32/181 highlights added or updated
33/181 highlights added or updated
34/181 highlights added or updated
35/181 highlights added or updated
36/181 highlights added or updated
37/181 highlights added or updated
38/181 highlights added or updated
39/181 highlights added or updated
40/181 highlights added or updated
41/181 highlights added or updated
42/181 highlights added or updated
43/181 highlights added or updated
44/181 highlights added or updated
45/181 highlights added or updated
46/181 highlights added or updated
47/181 highlights added or updated
48/181 highlights added or updated
49/181 highlights added or updated
50/181 highlights added or updated
51/181 highlights added or updated
52/181 highlights added or updated
53/181 highlights added or updated
54/181 highlights added or updated
55/181 highlights added or updated
56/181 highlights added or updated
57/181 highlights added or updated
58/181 highlights added or updated
59/181 highlights added or updated
60/181 highlights added or updated
61/181 highlights added or updated
62/181 highlights added or updated
63/181 highlights added or updated
64/181 highlights added or updated
65/181 highlights added or updated
66/181 highlights added or updated
67/181 highlights added or updated
68/181 highlights added or updated
69/181 highlights added or updated
70/181 highlights added or updated
71/181 highlights added or updated
72/181 highlights added or updated
73/181 highlights added or updated
74/181 highlights added or updated
75/181 highlights added or updated
76/181 highlights added or updated
77/181 highlights added or updated
78/181 highlights added or updated
79/181 highlights added or updated
80/181 highlights added or updated
81/181 highlights added or updated
82/181 highlights added or updated
83/181 highlights added or updated
84/181 highlights added or updated
85/181 highlights added or updated
86/181 highlights added or updated
87/181 highlights added or updated
88/181 highlights added or updated
89/181 highlights added or updated
90/181 highlights added or updated
91/181 highlights added or updated
92/181 highlights added or updated
93/181 highlights added or updated
94/181 highlights added or updated
95/181 highlights added or updated
96/181 highlights added or updated
97/181 highlights added or updated
98/181 highlights added or updated
99/181 highlights added or updated
100/181 highlights added or updated
101/181 highlights added or updated
102/181 highlights added or updated
103/181 highlights added or updated
104/181 highlights added or updated
105/181 highlights added or updated
106/181 highlights added or updated
107/181 highlights added or updated
108/181 highlights added or updated
109/181 highlights added or updated
110/181 highlights added or updated
111/181 highlights added or updated
112/181 highlights added or updated
113/181 highlights added or updated
114/181 highlights added or updated
115/181 highlights added or updated
116/181 highlights added or updated
117/181 highlights added or updated
118/181 highlights added or updated
119/181 highlights added or updated
120/181 highlights added or updated
121/181 highlights added or updated
122/181 highlights added or updated
123/181 highlights added or updated
124/181 highlights added or updated
125/181 highlights added or updated
126/181 highlights added or updated
127/181 highlights added or updated
128/181 highlights added or updated
129/181 highlights added or updated
130/181 highlights added or updated
131/181 highlights added or updated
132/181 highlights added or updated
133/181 highlights added or updated
134/181 highlights added or updated
135/181 highlights added or updated
136/181 highlights added or updated
137/181 highlights added or updated
138/181 highlights added or updated
139/181 highlights added or updated
140/181 highlights added or updated
141/181 highlights added or updated
142/181 highlights added or updated
143/181 highlights added or updated
144/181 highlights added or updated
145/181 highlights added or updated
146/181 highlights added or updated
147/181 highlights added or updated
148/181 highlights added or updated
149/181 highlights added or updated
150/181 highlights added or updated
151/181 highlights added or updated
152/181 highlights added or updated
153/181 highlights added or updated
154/181 highlights added or updated
155/181 highlights added or updated
156/181 highlights added or updated
157/181 highlights added or updated
158/181 highlights added or updated
159/181 highlights added or updated
160/181 highlights added or updated
161/181 highlights added or updated
162/181 highlights added or updated
163/181 highlights added or updated
164/181 highlights added or updated
165/181 highlights added or updated
166/181 highlights added or updated
167/181 highlights added or updated
168/181 highlights added or updated
169/181 highlights added or updated
170/181 highlights added or updated
171/181 highlights added or updated
172/181 highlights added or updated
173/181 highlights added or updated
174/181 highlights added or updated
175/181 highlights added or updated
176/181 highlights added or updated
177/181 highlights added or updated
178/181 highlights added or updated
179/181 highlights added or updated
180/181 highlights added or updated
181/181 highlights added or updated
Appending updated highlight data to categoriesObject...
Fetching tags for 181 highlights in bulk via CSV export...
Opening new Chrome browser window...

DevTools listening on ws://127.0.0.1:54700/devtools/browser/cfaaac0b-872e-4eb0-979d-69e6dc6e3c01
Logging into readwise using credentials provided in readwiseMetadata
Log-in successful! Redirecting to export page...
Redirect successful! Waiting for CSV export...
Waiting for download to complete...
Opening a new tab and redirecting to chrome://downloads...
Download complete! Fetching filename from the last download...
readwise-data.csv successfully added to H:\Dropbox\Obsidian\PRISM\.obsidian\scripts\readwise2directory-master
Closing Chrome browser window...
1/181 highlights matched with 0/0 tags
2/181 highlights matched with 0/0 tags
3/181 highlights matched with 0/0 tags
4/181 highlights matched with 0/0 tags
5/181 highlights matched with 0/0 tags
6/181 highlights matched with 0/0 tags
7/181 highlights matched with 0/0 tags
8/181 highlights matched with 0/0 tags
9/181 highlights matched with 0/0 tags
10/181 highlights matched with 0/0 tags
11/181 highlights matched with 0/0 tags
12/181 highlights matched with 0/0 tags
13/181 highlights matched with 0/0 tags
14/181 highlights matched with 0/0 tags
15/181 highlights matched with 0/0 tags
16/181 highlights matched with 0/0 tags
17/181 highlights matched with 0/0 tags
18/181 highlights matched with 0/0 tags
19/181 highlights matched with 0/0 tags
20/181 highlights matched with 0/0 tags
21/181 highlights matched with 0/0 tags
22/181 highlights matched with 0/0 tags
23/181 highlights matched with 0/0 tags
24/181 highlights matched with 0/0 tags
25/181 highlights matched with 0/0 tags
26/181 highlights matched with 0/0 tags
27/181 highlights matched with 0/0 tags
28/181 highlights matched with 0/0 tags
29/181 highlights matched with 0/0 tags
30/181 highlights matched with 0/0 tags
31/181 highlights matched with 0/0 tags
32/181 highlights matched with 0/0 tags
33/181 highlights matched with 0/0 tags
34/181 highlights matched with 0/0 tags
35/181 highlights matched with 0/0 tags
36/181 highlights matched with 0/0 tags
37/181 highlights matched with 0/0 tags
38/181 highlights matched with 0/0 tags
39/181 highlights matched with 0/0 tags
40/181 highlights matched with 0/0 tags
41/181 highlights matched with 0/0 tags
42/181 highlights matched with 0/0 tags
43/181 highlights matched with 0/0 tags
44/181 highlights matched with 0/0 tags
45/181 highlights matched with 0/0 tags
46/181 highlights matched with 0/0 tags
47/181 highlights matched with 0/0 tags
48/181 highlights matched with 0/0 tags
49/181 highlights matched with 0/0 tags
50/181 highlights matched with 0/0 tags
51/181 highlights matched with 0/0 tags
52/181 highlights matched with 0/0 tags
-67 highlights removed from 7146533
0 highlights discarded
0 tags updated with hashtags
Stealing Fire created or updated
Eleanor Oliphant Is Completely Fine created or updated
Happiness by Design created or updated
Life's a Pitch created or updated
Felt Time created or updated
How to Use Readwise created or updated
Happiness by Design created or updated
Felt Time created or updated
11 new markdown notes created and -3 markdown notes updated
Script complete
```
